CREATE DATABASE bdPartido
USE bdPartido

select * from tbFiliado

--Função LIKE
SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS COM NOME ANTONIO' FROM tbFiliado
WHERE NOME_DO_FILIADO LIKE 'ANTONIO%'

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS COM SOBRENOME SEBASTIÃO' FROM tbFiliado
WHERE NOME_DO_FILIADO LIKE '%SEBASTIÃO%'

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS COM OS NO FINAL DO NOME' FROM tbFiliado
WHERE NOME_DO_FILIADO LIKE '%OS'

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS QUE MORAM NO MUNICÍPIO DE SÃO FÉLIX' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%SÃO FÉLIX%'

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS QUE MORAM NO MUNICIPIO DE INHAMBUPE' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%INHAMBUPE%'

SELECT NOME_DO_MUNICIPIO AS 'NOME DOS MUNICÍPIOS QUE COMECEM COM O NOME SANTA' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'SANTA%'

SELECT NOME_DO_MUNICIPIO AS 'NOME DOS MNICIPIOS QUE COMECEM COM A LETRA E' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE 'E%'

SELECT NOME_DO_MUNICIPIO AS 'NOME DOS MUNICÍPIOS QUE CONTENHA CRUZ EM SEU NOME' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%CRUZ%'

SELECT NOME_DO_MUNICIPIO AS 'NOME DOS MUNICÍPIOS QUE CONTENHA DE EM SEU NOME' FROM tbFiliado
WHERE NOME_DO_MUNICIPIO LIKE '%DE%'

--Função BETWEEN
SELECT NOME_DO_FILIADO AS 'FILIADOS CADASTRADOS ENTRE OS ANOS DE 1990 E 2000', CONVERT(VARCHAR(10),DATA_DA_FILIACAO,103) AS 'DATA DA FILIAÇÃO' FROM tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '01/01/1990' AND '01/01/2000'

SELECT NOME_DO_FILIADO AS 'FILIADOS CADASTRADOS ENTRE 02/01/2010 E 01/03/2010', CONVERT(VARCHAR(10),DATA_DA_FILIACAO,103) AS 'DATA DA FILIAÇÃO' FROM tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '02/01/2010' AND '01/03/2010'

SELECT NOME_DO_FILIADO, CONVERT(VARCHAR(10),DATA_DA_FILIACAO,103) AS 'DATA DA FILIAÇÃO' FROM tbFiliado
WHERE DATA_DA_FILIACAO BETWEEN '01/01/2007' AND '31/12/2007'

--OPERADOR "="
SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS DA ZONA ELEITORAL 203' FROM tbFiliado
WHERE ZONA_ELEITORAL = 203

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS DA ZONA ELEITORAL 180' FROM tbFiliado
WHERE ZONA_ELEITORAL = 180

SELECT NOME_DO_FILIADO AS 'NOME DOS FILIADOS DA ZONA ELEITORAL 199' FROM tbFiliado
WHERE ZONA_ELEITORAL = 199

--FUNÇÃO MAX E MIN
SELECT MAX (ZONA_ELEITORAL) AS 'NÚMERO DA MAIOR ZONA ELEITORAL' FROM tbFiliado

SELECT MIN (ZONA_ELEITORAL) AS 'NÚMERO DA MENOR ZONA ELEITORAL' FROM tbFiliado

SELECT ZONA_ELEITORAL FROM tbFiliado
WHERE ZONA_ELEITORAL > 205

--FUNÇÃO UPDATE
UPDATE tbFiliado
SET SIGLA_DO_PARTIDO = 'PV'
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX'
UPDATE tbFiliado
SET NOME_DO_PARTIDO = 'PARTIDO VERDE'
WHERE NOME_DO_MUNICIPIO = 'SÃO FÉLIX'

UPDATE tbFiliado
SET SIGLA_DO_PARTIDO = 'PSDB'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'
UPDATE tbFiliado
SET NOME_DO_PARTIDO = 'PARTIDO DA SOCIAL-DEMOCRACIA BRASILEIRA'
WHERE NOME_DO_MUNICIPIO = 'ENCRUZILHADA'

UPDATE tbFiliado
SET NOME_DO_FILIADO = 'JORGE LUIS MAGALHÃES DOS SANTOS'
WHERE NOME_DO_FILIADO = 'JORGE LUIS FERREIRA DOS SANTOS'

UPDATE tbFiliado
SET NOME_DO_FILIADO = 'RENATA XAVIER RODRIGUES'
WHERE NOME_DO_FILIADO = 'BENTA XAVIER RODRIGUES'

UPDATE tbFiliado
SET NOME_DO_FILIADO = 'NOEL LEITE DA SILVA'
WHERE NOME_DO_FILIADO = 'NOE LEITE DA SILVA'

UPDATE tbFiliado
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'ELIEL ALMEIDA SILVA'

UPDATE tbFiliado
SET SITUACAO_DO_REGISTRO = 'REGULAR'
WHERE NOME_DO_FILIADO = 'JOSIENE ANDRADE DE SOUZA'

UPDATE tbFiliado
SET SITUACAO_DO_REGISTRO = 'DESFILIADO'
WHERE NOME_DO_FILIADO = 'ALINE DE SOUZA'

--FUNÇÃO ALTER TABLE
ALTER TABLE tbFiliado ADD Sexo char(1)


